service:
  ecommerce:
    image: postgres:18
    container_name: ecommerce
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/n
    healthcheck:
      test: [
          'CMD',
          'pg_isready',
          '-U', # user
          'ecommerce',
          '-d', # database
          'ecommerce_db',
          '-h', # ping ip-adress
          '127.0.0.1',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - db_network

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - pgadmin.env
    ports:
      - '8080:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - ecommerce
    networks:
      - db_network

volumes:
  postgres_data:
  pgadmin_data:
